/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.opencsv.CSVWriter;
import diviceController.GlobalValues;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author ASUS1
 */
public class ExportCSV extends javax.swing.JFrame {

    /**
     * Creates new form ExportCSV
     */
    public ExportCSV() {

        initComponents();
        this.setTitle("TỔNG CÔNG TY CÔNG NGHỆ - VIỄN THÔNG TOÀN CẦU");
        ImageIcon img1 = new ImageIcon(getClass().getResource("/logo-line-01.png"));
        this.setIconImage(img1.getImage());
        File files = new File(GlobalValues.EXPORT_CSV);
        if (files.exists()){
            this.getTxtLinkThuMuc().setEnabled(false);
            this.getTxtLinkThuMuc().setText(GlobalValues.EXPORT_CSV);
            this.getTxtLinkCSV().setEnabled(true);
            this.btnCreateCSV.setEnabled(false);
        }else {
            this.getTxtLinkThuMuc().setEnabled(true);
            this.getTxtLinkCSV().setEnabled(false);
            this.btnCreateCSV.setEnabled(true);
        }
    }

    public JButton getjButton1() {
        return btnCreateCSV;
    }

    public void setjButton1(JButton jButton1) {
        this.btnCreateCSV = jButton1;
    }

    public JTextField getTxtLinkCSV() {
        return txtLinkCSV;
    }

    public void setTxtLinkCSV(JTextField txtLinkCSV) {
        this.txtLinkCSV = txtLinkCSV;
    }

    public JTextField getTxtLinkThuMuc() {
        return txtLinkThuMuc;
    }

    public void setTxtLinkThuMuc(JTextField txtLinkThuMuc) {
        this.txtLinkThuMuc = txtLinkThuMuc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLinkThuMuc = new javax.swing.JTextField();
        txtLinkCSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCreateCSV = new javax.swing.JButton();
        btnExportCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Xuất CSV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel2.setText("Link đường dẫn thư mục gốc :");

        jLabel3.setText("Link đường dẫn File CSV :");

        btnCreateCSV.setText("Tạo Link thư mục");
        btnCreateCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCSVActionPerformed(evt);
            }
        });

        btnExportCSV.setText("Xuất File CSV");
        btnExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnExportCSVActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLinkCSV, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(txtLinkThuMuc)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCreateCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportCSV)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLinkThuMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLinkCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCSV)
                    .addComponent(btnExportCSV))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportCSVActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btnExportCSVActionPerformed
        if(GlobalValues.checkRar && GlobalValues.CHECK_FACE){
            List<String[]> list = new ArrayList<>();
            String[] header = {"id", "CCCD", "Họ và tên", "Ngày sinh","Giới tính","Dân tộc","Tôn giáo","Quê quán","Thường trú", "ĐDND", "Ngày cấp", "Hết hạn", "Tên Bố", "Tên Mẹ", "CMND", "Vợ/Chồng"};
            String[] record1 = new String[]{
                    "1",

            };
            list.add(header);
            list.add(record1);
            java.util.List<String[]> csvData = list;
            int ranNum = ThreadLocalRandom.current().nextInt(1,101);
            String pathCSV = GlobalValues.EXPORT_CSV+"/EId_"+ranNum+".csv";
            FileOutputStream os = new FileOutputStream(pathCSV);
            os.write(0xef);
            os.write(0xbb);
            os.write(0xbf);
            try (CSVWriter csvWrite = new CSVWriter(new OutputStreamWriter(os))) {
                csvWrite.writeAll(csvData);
                this.getTxtLinkCSV().setText(pathCSV);
                JOptionPane.showConfirmDialog(this, "Xuất CSV thành công","Thành công!",JOptionPane.OK_CANCEL_OPTION);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }else {
            JOptionPane.showConfirmDialog(this, "Cần xác thực trước khi xuất CSV","Cảnh báo!",JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_btnExportCSVActionPerformed

    private void btnCreateCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCSVActionPerformed
        File files = new File(GlobalValues.EXPORT_CSV);
        if (!files.exists()) {
            System.out.println("checktao file" +files.mkdirs());
            this.btnCreateCSV.setEnabled(false);
            this.txtLinkThuMuc.setText(GlobalValues.EXPORT_CSV);
            this.txtLinkThuMuc.setEnabled(false);
            this.btnExportCSV.setEnabled(true);
            this.txtLinkCSV.setEnabled(true);
            GlobalValues.Check_CSV = true;
            System.out.println("Multiple directories are created!");
        } else {

            System.out.println("Failed to create multiple directories!");
        }
    }//GEN-LAST:event_btnCreateCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportCSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCSV;
    private javax.swing.JButton btnExportCSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtLinkCSV;
    private javax.swing.JTextField txtLinkThuMuc;
    // End of variables declaration//GEN-END:variables
}
